services:
  mcp-nexus:
    container_name: mcp-nexus
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - NEXT_PUBLIC_MCP_PORT=${NEXT_PUBLIC_MCP_PORT}
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - apps/web/.env
    environment:
      - TZ=Europe/Minsk
      - NODE_ENV=production
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
